### ISSUE TITLE
Payload won't execute on windows

### ISSUE THREAD

**Issue by arthurvanderwal81** [ebursztein/malusb#6]
The windows payload relies on that windows will somehow automatically enter the payload in a command window or in the 'run' program. However this is not how windows works.

When USB drive gets inserted, and it starts to send out the payload key strokes, it will result in nothing, or at the very best a focussed text box to receive these keystrokes. (similar issue has been reported for Mac).

To fix this on windows send a Windows-key + r key combination before the payload to open the run program dialog.

**Comment by jmichelp** [comment]
That's exactly what is being done here: https://github.com/ebursztein/malusb/blob/master/payload/payload.c#L343

And this function, `win_open_execute` is called before any windows payload injection.

**Comment by arthurvanderwal81** [comment]
You're absolutely right! My oversight
